spring:
  application:
    name: customerApplication
  datasource:
    url: jdbc:mysql://139.129.37.84:3306/xiaozhong_dianping?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: budouer
    password: 'BuDou&123'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  data:
    redis:
      database: 0
      host: 139.129.37.84
      port: 6379
      password: Yt526526
      timeout: 500000
      lettuce:
        pool:
          max-active: 32
          max-wait: -1
          max-idle: 16
          min-idle: 8
  mvc:
    static-path-pattern: /static/**
  resources:
    mime:
      mappings:
        .jpg: image/jpeg
        .jpeg: image/jpeg
        .png: image/png
  web:
    resources:
      static-locations:
        [ classpath:/static/]
      chain:
        strategy:
          content:
            enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fudan.xiaozhong_dianping.shop.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 121.43.228.48:9876
  transaction:
    topic: demo-topic
    producer:
      group: transaction-producer-group

server:
  port: 8088
fudan:
  jwt:
    user-secret-key: fudan_university_security_key_for_jwt_authentication_2025
    user-ttl: 360000000000
    user-token-name: authentication

# 配置日志级别
logging:
  level:
    root: INFO
    com.fudan.xiaozhong_dianping: DEBUG  # 设置整个项目的日志级别为DEBUG
    com.fudan.xiaozhong_dianping.shop: DEBUG
    com.fudan.xiaozhong_dianping.shop.controller.ShopController: DEBUG
    com.fudan.xiaozhong_dianping.shop.service.impl.ShopServiceImpl: DEBUG
    com.fudan.xiaozhong_dianping.shop.mapper: DEBUG
    com.fudan.xiaozhong_dianping.groupbuy: DEBUG
    com.fudan.xiaozhong_dianping.groupbuy.controller.GroupBuyController: DEBUG
    com.fudan.xiaozhong_dianping.groupbuy.service.impl.GroupBuyServiceImpl: DEBUG
    com.fudan.xiaozhong_dianping.groupbuy.repository: DEBUG
    # 关闭Hibernate和JPA日志
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  return-pageinfo: check

