spring:
  application:
    name: customerApplication
  datasource:
    url: jdbc:mysql://139.129.37.84:3306/xiaozhong_dianping
    username: budouer
    password: 'BuDou&123'
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port:
    8088
